actionDict = {
    #File Actions
    'ACTION_FILE_CREATE': 'u',
    'ACTION_FILE_DELETE': 'E',
    'ACTION_FILE_LAST_WRITE': 'GG',
    'ACTION_FILE_MOD_OPEN': 'uu',
    'ACTION_FILE_OPEN_DELETE': 'EE',
    'ACTION_FILE_OPEN_EXECUTE': 'p',
    'ACTION_FILE_OPEN_READ': 'v',
    'ACTION_FILE_OPEN_SET_ATTRIBUTES': 'c',
    'ACTION_FILE_OPEN_SET_SECURITY': 'j' ,
    'ACTION_FILE_OPEN_WRITE': 'uG',
    'ACTION_FILE_READ': 'vv',
    'ACTION_FILE_RENAME': 'H' ,
    'ACTION_FILE_TRUNCATE': 'D',
    'ACTION_FILE_UNDELETE': 'ue',
    'ACTION_FILE_WRITE': 'G',
    'ACTION_WRITE_VALUE': 'gv',
    
    #Netconn Actions':
    'ACTION_CONNECTION_CREATE': 'o',
    'ACTION_CONNECTION_ESTABLISHED': 'i',
    'ACTION_CONNECTION_LISTEN': 's',
    'ACTION_CONNECTION_CLOSE': 'n',
    'ACTION_CONNECTION_CREATE_FAILED': 'oo',
    
    #REGMOD ACTIONS
    'ACTION_CREATE_KEY': 'K',
    'ACTION_DELETE_KEY': 'dk',
    'ACTION_DELETE_VALUE': 'dv',
    'ACTION_OPEN_KEY_DELETE': 'DK',
    'ACTION_OPEN_KEY_READ': 'kr',
    'ACTION_OPEN_KEY_WRITE': 'KK' ,
    'ACTION_LOAD_KEY': 'lk',
    
    #MODLOAD ACTIONS
    'ACTION_LOAD_MODULE': 't',
    
    #PROCSTART ACTIONS
    'ACTION_CREATE_PROCESS': 'pp',
    'ACTION_CREATE_PROCESS_EFFECTIVE': 'pe',
    'ACTION_PROCESS_DISCOVERED': 'pd',
    
    #PROCEND ACTIONS ,
    'ACTION_PROCESS_TERMINATE': 'I',

    #CROSSPROC ACTIONS
    'ACTION_DUP_PROCESS_HANDLE': 'dup',
    'ACTION_DUP_THREAD_HANDLE': 'db',
    'ACTION_OPEN_PROCESS_HANDLE': 'J',
    'ACTION_OPEN_THREAD_HANDLE': 'b',
    
    #SCRIPTLOAD ACTIONS
    'ACTION_LOAD_SCRIPT': 'pls'
}

